frontend/application/frontend/forms.py
# application/frontend/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, HiddenField, IntegerField

from wtforms.validators import DataRequired, Email


class SearchForm(FlaskForm):
    searched = StringField('Searched', validators=[DataRequired()])
    submit = SubmitField('Submit')

class LoginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Login')


class RegistrationForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    first_name = StringField('First name', validators=[DataRequired()])
    last_name = StringField('Last name', validators=[DataRequired()])
    email = StringField('Email address', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Register')


class OrderItemForm(FlaskForm):
    product_id = HiddenField(validators=[DataRequired()])
    quantity = IntegerField(validators=[DataRequired()])
    order_id = HiddenField()
    submit = SubmitField('Update')


class ItemForm(FlaskForm):
    product_id = HiddenField(validators=[DataRequired()])
    quantity = HiddenField(validators=[DataRequired()], default=1)

frontend/application/__init__.py
# application/__init__.py
import config
import os
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_login import LoginManager

login_manager = LoginManager()
bootstrap = Bootstrap()
UPLOAD_FOLDER = 'application/static/images'


def create_app():
    app = Flask(__name__, static_folder='static')
    app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER

    environment_configuration = os.environ['CONFIGURATION_SETUP']
    app.config.from_object(environment_configuration)

    login_manager.init_app(app)
    login_manager.login_message = "You must be login to access this page."
    login_manager.login_view = "frontend.login"

    bootstrap.init_app(app)

    with app.app_context():
        from .frontend import frontend_blueprint
        app.register_blueprint(frontend_blueprint)

        return app

frontend/application/frontend/__init__.py
# application/frontend/__init__.py
from flask import Blueprint

frontend_blueprint = Blueprint('frontend', __name__)

from . import views

frontend/application/frontend/views.py
# application/frontend/views.py
import requests
from . import forms
from . import frontend_blueprint
from .. import login_manager
from .api.UserClient import UserClient
from .api.ProductClient import ProductClient
from .api.OrderClient import OrderClient
from flask import render_template, session, redirect, url_for, flash, request

from flask_login import current_user


@login_manager.user_loader
def load_user(user_id):
    return None


@frontend_blueprint.route('/', methods=['GET'])
def home():
    if current_user.is_authenticated:
        session['order'] = OrderClient.get_order_from_session()

    try:
        products = ProductClient.get_products()
    except requests.exceptions.ConnectionError:
        products = {
            'results': []
        }

    return render_template('home/index.html', products=products)


@frontend_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    form = forms.RegistrationForm(request.form)
    if request.method == "POST":
        if form.validate_on_submit():
            username = form.username.data

            # Search for existing user
            user = UserClient.does_exist(username)
            if user:
                # Existing user found
                flash('Please try another username', 'error')
                return render_template('register/index.html', form=form)
            else:
                # Attempt to create new user
                user = UserClient.post_user_create(form)
                if user:
                    flash('Thanks for registering, please login', 'success')
                    return redirect(url_for('frontend.login'))

        else:
            flash('Errors found', 'error')

    return render_template('register/index.html', form=form)


@frontend_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('frontend.home'))
    form = forms.LoginForm()
    if request.method == "POST":
        if form.validate_on_submit():
            api_key = UserClient.post_login(form)
            if api_key:
                session['user_api_key'] = api_key
                user = UserClient.get_user()
                session['user'] = user['result']

                order = OrderClient.get_order()
                if order.get('result', False):
                    session['order'] = order['result']

                flash('Welcome back, ' + user['result']['username'], 'success')
                return redirect(url_for('frontend.home'))
            else:
                flash('Cannot login', 'error')
        else:
            flash('Errors found', 'error')
    return render_template('login/index.html', form=form)


@frontend_blueprint.route('/logout', methods=['GET'])
def logout():
    session.clear()  # type: ignore
    return redirect(url_for('frontend.home'))


@frontend_blueprint.route('/product/<slug>', methods=['GET', 'POST'])
def product(slug):
    response = ProductClient.get_product(slug)
    item = response['result']

    form = forms.ItemForm(product_id=item['id'])

    if request.method == "POST":
        if 'user' not in session:
            flash('Please login', 'error')
            return redirect(url_for('frontend.login'))
        order = OrderClient.post_add_to_cart(product_id=item['id'], qty=1)
        new_func(order)
        flash('Order has been updated', 'success')
    return render_template('product/index.html', product=item, form=form)

def new_func(order):
    session['order'] = order['result']


@frontend_blueprint.route('/checkout', methods=['GET'])
def summary():
    if 'user' not in session:
        flash('Please login', 'error')
        return redirect(url_for('frontend.login'))

    if 'order' not in session:
        flash('No order found', 'error')
        return redirect(url_for('frontend.home'))
    order = OrderClient.get_order()

    if len(order['result']['items']) == 0:
        flash('No order found', 'error')
        return redirect(url_for('frontend.home'))

    OrderClient.post_checkout()

    return redirect(url_for('frontend.thank_you'))

@frontend_blueprint.route('/order/thank-you', methods=['GET'])
def thank_you():
    if 'user' not in session:
        flash('Please login', 'error')
        return redirect(url_for('frontend.login'))

    if 'order' not in session:
        flash('No order found', 'error')
        return redirect(url_for('frontend.home'))

    session.pop('order', None)  # type: ignore
    flash('Thank you for your order', 'success')

    return render_template('order/thankyou.html')
@frontend_blueprint.context_processor
def base():
    form = forms.SearchForm()
    return dict(form=form)
@frontend_blueprint.route('/search', methods=['GET', 'POST'])
def search():
   form = forms.SearchForm()
   
   if form.validate_on_submit():
    try:
        p=[]
        searched = form.searched.data  # Get the searched term from the form
        products = ProductClient.get_product(searched)
        url = f"http://localhost:5000/product/{searched}"  # Manually construct the URL
        return redirect(url)
    except requests.exceptions.ConnectionError:
        products = {
            'results': []
        }

    return render_template('home/index.html/', products=products)

frontend/application/templates/_messages.html
{% for error_message in get_flashed_messages(category_filter=["error"]) %}
  <div class="alert alert-danger alert-dismissible">{{ error_message }}</div>
{% endfor %}

{% for success_message in get_flashed_messages(category_filter=["success"]) %}
  <div class="alert alert-success alert-dismissible">{{ success_message }}</div>
{% endfor %}

{% for info_message in get_flashed_messages(category_filter=["info"]) %}
  <div class="alert alert-info alert-dismissible">{{ info_message }}</div>
{% endfor %}

frontend/application/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>


    {% block styles %}

        <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
              integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
              crossorigin="anonymous">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    {% endblock %}


</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

frontend/application/templates/base_col_1.html
{% extends "base.html" %}

{% block content %}
{% include 'nav_header.html' %}
    <div class="container" id="outer-container">

        {% include '_messages.html' %}
        {% block pageContent %} {% endblock %}

    </div>
{% endblock %}

frontend/application/templates/base_col_2.html
{% extends "base.html" %}



{% block content %}
{% include 'nav_header.html' %}
    <div class="container">

        {% include '_messages.html' %}
          <div class="col-md-12">
              <div class="col-md-3">

              </div>
              <div class="col-md-9">
                {% block pageContent %} {% endblock %}
              </div>
          </div>
    </div>
{% endblock %}

frontend/application/templates/home/index.html
{% extends "base_col_1.html" %}
{% block title %}Home Page{% endblock %}

{% block pageContent %}

{% if products | length > 0 %}
    {% for product in products.results %}

{% set url = "/product/" + product.slug %}
{% set imageSRC = "images/" + product.image %}

<div class="col-md-4">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h2 class="panel-title">{{ product.name }}</h2>
        </div>
        <div class="panel-body">
            <div class="img-block">
                <img src="{{ url_for('static', filename=imageSRC) }}" width="100%"/>
            </div>
        </div>
        <div class="panel-footer">
            <div class="container">
                <div class="label label-info">Price: {{ product.price }} $</div>
                <a class="btn btn-success" href="{{ url }}">View more</a>
            </div>
        </div>
    </div>
</div>
{% endfor %}

    {% else %}
        <strong>No products found.</strong>
    {% endif %}


{% endblock %}

frontend/application/templates/login/index.html
{% extends "base_col_1.html" %}
{% from "macros/_macros_form.html" import render_field %}
{% block title %}Login{% endblock %}

{% block pageContent %}
    <h1>Login</h1>
    <strong>{{ message }}</strong>
    <!-- Login form -->
    <form method="post">
    {{ form.hidden_tag() }}
    {{ render_field(form.username) }}
    {{ render_field(form.password) }}
    {{ form.submit(class_="btn btn-success pull-right") }}


    </form>

{% endblock %}

frontend/application/templates/macros/_macros_basket.html
{{ session['order'] | pprint }}
{% macro count_items()%}
{% set counter = namespace(a=0) %}
    {% if session['order'] %}
        {% for item in session['order']['items'] %}
            {% set counter.a = counter.a + item['quantity'] %}
        {% endfor %}
    {% endif %}
{{ counter.a }}
{% endmacro %}

frontend/application/templates/macros/_macros_form.html
{% macro render_field(field) %}
  <div class="form-group">
      {{ field.label(class_="form-label") }}:
        {% if field.errors %}
            <span class="error">
            {% for error in field.errors %}
              {{ error }}
            {% endfor %}
            </span>
      {% endif %}


      {{ field(class_="form-control") }}
</div>
{% endmacro %}



{% macro render_field_without_label(field) %}
  <dd>{{ field(**kwargs)|safe }}
  {% if field.errors %}
    <span class="error">
    {% for error in field.errors %}
      {{ error }}
    {% endfor %}
    </span>
  {% endif %}
  </dd>
{% endmacro %}


{% macro render_boolean_field(field) %}
  <dd>{{ field(**kwargs)|safe }} {{ field.label }}
  {% if field.errors %}
    <span class="error">
    {% for error in field.errors %}
      {{ error }}
    {% endfor %}
    </span>
  {% endif %}
  </dd>
{% endmacro %}


{% macro render_errors(field) %}
  {% if field.errors %}
    <span class="error">
    {% for error in field.errors %}
      {{ error }}
    {% endfor %}
    </span>
  {% endif %}
{% endmacro %}

frontend/application/templates/nav_header.html
{% from "macros/_macros_basket.html" import count_items %}
<header class="row">
    <nav class="navbar navbar-default">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a href="/">Home</a></li>
                <form method="POST" action="{{ url_for('frontend.search') }}" class="d-flex">
                    {{ form.hidden_tag() }}
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search", name="searched">
                    <button class="btn btn-outline-sucondary" type="submit">
                      Search</button>
                  </form>
            </ul>
            <ul class="nav navbar-nav pull-right">
                {% if not session['user'] %}
                    <li><a href="/login">Login</a></li>
                    <li><a href="/register">Register</a></li>
                {% else %}
                    {% if session['role'] is true %}
                        <li><a href="/admin">Dashboard</a></li>
                        <li><a href="/logout">Logout</a></li>
                    {% else %}
                        <li><a href="/logout">Logout</a></li>
                    {% endif %}
                {% endif %}
                <li><a href="/checkout">Checkout <span class="badge">{{ count_items() }}</span></a></li>
            </ul>

        </div>
    </nav>
</header>

frontend/application/templates/order/thankyou.html
{% extends "base_col_1.html" %}
{% block title %}Thank you{% endblock %}

{% block pageContent %}
    <h1>Thank you</h1>
    <p>your order is being processed</p>
{% endblock %}

frontend/application/templates/product/index.html
{% extends "base_col_1.html" %}
{% from "macros/_macros_form.html" import render_field %}
{% block title %}Product page{% endblock %}

{% block pageContent %}

    {% set url = "/product/" + product.slug %}
    {% set imageSRC = "images/" + product.image %}
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h2 class="panel-title">{{ product.name }}</h2>
            </div>
            <div class="panel-body">
                <div class="img-block">
                    <img src="{{ url_for('static', filename=imageSRC) }}"/>
                </div>
            </div>
            <div class="panel-footer">
                <div class="container">
                    <div class="label label-default">Price: {{ product.price }}</div>
                    <form method="POST">
                        {{ form.hidden_tag() }}
                        <button type="submit" class="btn btn-success" id="buy-now">Add To Cart</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

frontend/application/templates/register/index.html
{% extends "base_col_1.html" %}
{% from "macros/_macros_form.html" import render_field %}
{% block title %}Register{% endblock %}

{% block pageContent %}
    <h1>Register</h1>
    <strong>{{ message }}</strong>
    <!-- Registration form -->
    <form method="post">
    {{ form.hidden_tag() }}
    {{ render_field(form.username) }}
    {{ render_field(form.first_name) }}
    {{ render_field(form.last_name) }}
    {{ render_field(form.email) }}
    {{ render_field(form.password) }}
    {{ form.submit(class_="btn btn-success pull-right") }}

    </form>

{% endblock %}

frontend/application/templates/search.html
{% extends "base_col_1.html" %}
{% block content %}
<br/>
<h2>you searched for</h2>
<p> {{ searched }}</p>
<br/>
{% for product in products %}
<p>{{ product.name }} </p>
{% endfor %}

{% endblock %}